package_assets: on
compress_assets: on

javascripts:
    all:
        - public/javascripts/vendor/jquery.min.js
        - public/javascripts/vendor/jquery-ui.min.js
        - public/javascripts/vendor/jquery.fileupload.js
        - public/javascripts/vendor/jquery.iframe-transport.js
        - public/javascripts/vendor/jquery.fileupload-ui.js
        - public/javascripts/vendor/mustache.js
        - public/javascripts/vendor/bootstrap.js
        - public/javascripts/vendor/tinycolor-min.js
        - public/javascripts/vendor/backbone-min.js
        - public/javascripts/vendor/underscore-min.js
        - public/javascripts/vendor/json2.js
        - public/javascripts/vendor/placeholder.js
        - public/javascripts/k-core.js
        - public/javascripts/k-util.js
        - public/javascripts/k-data.js
        - public/javascripts/k-manager.js
        - public/javascripts/k-component.js
        - public/javascripts/k-message.js
        - public/javascripts/k-validation.js
        - public/javascripts/k-form.js
        - public/javascripts/views/**/**/*.jst    
    
    kit:
        - public/javascripts/components/k-kit-steps.js
        - public/javascripts/components/k-kit-newstep.js
        - public/javascripts/components/k-kit-editstep.js
        - public/javascripts/components/k-kit-reorderstep.js
        - public/javascripts/components/k-kit-instructions-host.js
        - public/javascripts/components/k-kit-items.js
        - public/javascripts/components/k-kit-newitem.js
        - public/javascripts/components/k-kit-edititem.js
        - public/javascripts/components/k-kit-optionals.js
        - public/javascripts/components/k-kit-publish.js
        - public/javascripts/components/k-kit-params.js
        - public/javascripts/components/k-kit-image.js
        - public/javascripts/components/k-kit-customize.js
        - public/javascripts/components/k-kit-nav.js

    home:
        - public/javascripts/components/k-front.js

stylesheets:
    all:
        - public/stylesheets/vendor/bootstrap.min.css
        - public/stylesheets/vendor/jquery-ui.css
        - public/stylesheets/vendor/jquery-fileupload-ui.css
        - public/stylesheets/k-core.css
        - public/stylesheets/k-layout.css
        - public/stylesheets/k-typography.css
        
    home:
        - public/stylesheets/k-home.css
        
    kit:
        - public/stylesheets/k-kit.css
    
    browse:
        - public/stylesheets/k-kit.css
